if(typeof(require) !== "undefined"){
  //turret
	require("tourelledelabres");
  //walls
  require("mendingwall");
	require("anti");
  //units
  //mechas
	require("envahisseur");
  //power
  //crafting
	require("dd");
	require("grif");
	require("com");
	require("am");
	require("vib");
	require("st");
  //rest
	require("soundmine");
	require("relief");
	require("effectlib");
	require("funclib");
}
